name: Publish CLI

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    # if: github.repository == 'mobile-dev-inc/maestro'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - uses: gradle/gradle-build-action@v2

      - name: Publish CLI
        run: ./gradlew :maestro-cli:jreleaserFullRelease --no-daemon --no-parallel
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print jReleaser log
        if: always()
        run: cat maestro-cli/build/jreleaser/trace.log
